# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 16:05
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('get_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
