# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20180123_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/home/ivan/django_project/mysite/static/forum/images/user.png', null=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
