# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20180123_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/home/ivan/django_project/mysite/media/image/2018/01/23', null=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
