# Generated by Django 2.1.2 on 2018-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20180123_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/default/user.png', null=True, upload_to='image/%Y/%m/%d'),
        ),
    ]
